name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  elixir-checks:
    name: Elixir Checks
    uses: primait/shared-github-actions/.github/workflows/elixir-ci.yml@elixir-ci-v3
    with:
      version-file: ".tool-versions"
      enable-credo: false
      enable-dialyzer: true
      enable-tests: true
